.PHONY: clean tesis

tesis: slides.tex
	pdflatex slides.tex

clean:
	rm -f slides.aux
	rm -f slides.toc
	rm -f slides.blg
	rm -f slides.log
	rm -f slides.synctex.gz
	rm -f slides.out
	rm -f slides.nav
	rm -f slides.snm